export const sectorsClasifications = {
  "'artisanale'": [
    "Ambulance",
    "Bijouterie - Joaillerie",
    "Biscuiterie",
    "Boucherie - Charcuterie",
    "Boulangerie - Pâtisserie",
    "Caviste",
    "Carrelage et sols",
    "Carrosserie",
    "Chocolaterie - confiserie",
    "Cordonnerie",
    "Couverture",
    "Cuisiniste",
    "Déménagement",
    "Démolition",
    "Ébénisterie",
    "Électricité",
    "Entretien et réparation de véhicules",
    "Fabrication de boissons alcoolisées",
    "Fabrication de textiles",
    "Ferronnerie",
    "Fleuriste",
    "Fromagerie",
    "Institut de beauté",
    "Maçonnerie",
    "Menuiserie",
    "Paysagiste",
    "Peinture en bâtiment",
    "Plâtrerie - Isolation",
    "Plomberie-chauffage",
    "Poissonnerie",
    "Restauration rapide à livrer ou à emporter",
    "Salon de coiffure",
    "Traiteur",
    "Travaux publics",
    "Verrerie",
    "Autre activité artisanale",
  ],
  "'commerciale ou industrielle'": [
    "Agence de sécurité",
    "Agence de voyage",
    "Agent commercial",
    "Agence immobilière",
    "Bar, café, débit de tabac",
    "Commerce de détail alimentaire",
    "Commerce de détail non alimentaire",
    "Commerce de gros",
    "Commerce de véhicules",
    "Crèche",
    "Diagnostic immobilier",
    "E-commerce",
    "Galerie d'art",
    "Hôtellerie",
    "Jardinerie",
    "Location d'équipements et de matériels",
    "Optique et lunetterie",
    "Presse et médias",
    "Industrie",
    "Restauration traditionnelle",
    "Restauration rapide sur place",
    "Salle de sport - fitness",
    "Services administratifs",
    "Services à la personne",
    "Spectacle vivant",
    "Start-up",
    "Taxi",
    "Transport léger de marchandises",
    "Transport lourd de marchandises",
    "VTC",
    "Autre activité commerciale",
  ],
  "'libérale'": [
    "Agence de communication ou publicité",
    "Agence marketing",
    "Agence web",
    "Agent général d'assurance",
    "Architecte",
    "Architecte d'intérieur",
    "Auto-école",
    "Avocat",
    "Bureau d'études",
    "Cabinet de diététique",
    "Coach sportif",
    "Conseil et activités informatiques",
    "Consulting et conseil",
    "Courtage en assurance",
    "Courtage en financement",
    "Designer",
    "Décoration d'intérieur",
    "Enseignement privé",
    "Formation",
    "Géomètre-expert",
    "Graphiste",
    "Kinésithérapie",
    "Médecine",
    "Médecine douce",
    "Ostéopathie",
    "Pharmacie",
    "Vétérinaire",
    "Autre activité libérale",
  ],
};
