package cqrs

import (
	"github.com/hashicorp/go-multierror"
	"github.com/pkg/errors"
	eventstream "gitlab.com/le-coin-des-entrepreneurs/backend-app/event_stream"
	"gitlab.com/le-coin-des-entrepreneurs/backend-app/event_stream/infrastructure/kafka"
	"gitlab.com/le-coin-des-entrepreneurs/backend-app/pkg/logging"
)

var CQRSFacade *Facade

type FacadeConfig struct {
	GenerateCommandsTopic func(commandName interface{}) string

	// CommandHandlers return command handlers which should be executed.
	CommandHandlers func(commandBus *kafka.CommandBusWriteStream, eventBus *kafka.EventBusWriteStream) []CommandHandler

	// CommandsPublisher is writer used to publish commands.
	CommandsPublisher eventstream.Writer

	// CommandsConsumerConstructor is constructor for consumers subscribed to messages.
	// It will be called for every command handler.
	// It allows you to create separated customized consumers for every command handler.
	CommandsConsumerConstructor ConsumerConstructor

	// GenerateEventsTopic generates topic name based on the event name.
	// Event name is generated by IEventMessageMarshaler's GenerateName method.
	//
	// It allows you to use topic per command or one topic for every command. [todo - add to doc]
	GenerateEventsTopic func(eventName interface{}) string

	// EventHandlers return event handlers which should be executed.
	EventHandlers func(commandBus *kafka.CommandBusWriteStream, eventBus *kafka.EventBusWriteStream) []EventHandler

	// EventsPublisher is writer used to publish events.
	EventsPublisher eventstream.Writer

	// EventsSubscriberConstructor is constructor for subscribers which will subscribe for messages.
	// It will be called for every event handler.
	// It allows you to create separated customized Subscriber for every event handler.
	EventsSubscriberConstructor ConsumerConstructor

	// Router is a Watermill router, which will be used to handle events and commands.
	// Router handlers will be automatically generated by AddHandlersToRouter of Command and Event handlers.
	Router *eventstream.Router

	CommandEventMarshaler eventstream.IEventMessageMarshaler

	Logger logging.BCPLogger
}

func (c FacadeConfig) Validate() error {
	var err error

	if c.CommandsEnabled() {
		if c.GenerateCommandsTopic == nil {
			err = multierror.Append(err, errors.New("GenerateCommandsTopic is nil"))
		}
		if c.CommandsConsumerConstructor == nil {
			err = multierror.Append(err, errors.New("CommandsConsumerConstructor is nil"))
		}
		if c.CommandsPublisher == nil {
			err = multierror.Append(err, errors.New("CommandsPublisher is nil"))
		}
	}
	if c.EventsEnabled() {
		if c.GenerateEventsTopic == nil {
			err = multierror.Append(err, errors.New("GenerateEventsTopic is nil"))
		}
		if c.EventsSubscriberConstructor == nil {
			err = multierror.Append(err, errors.New("EventsSubscriberConstructor is nil"))
		}
		if c.EventsPublisher == nil {
			err = multierror.Append(err, errors.New("EventsPublisher is nil"))
		}
	}

	if c.Router == nil {
		err = multierror.Append(err, errors.New("Router is nil"))
	}
	if c.Logger == nil {
		err = multierror.Append(err, errors.New("Logger is nil"))
	}
	if c.CommandEventMarshaler == nil {
		err = multierror.Append(err, errors.New("CommandEventMarshaler is nil"))
	}

	return err
}

func (c FacadeConfig) EventsEnabled() bool {
	return c.GenerateEventsTopic != nil || c.EventsPublisher != nil || c.EventsSubscriberConstructor != nil
}

func (c FacadeConfig) CommandsEnabled() bool {
	return c.GenerateCommandsTopic != nil || c.CommandsPublisher != nil || c.CommandsConsumerConstructor != nil
}

// Facade is a facade for creating the Command and Event buses and processors.
// It was created to avoid boilerplate, when using CQRS in the standard way.
// You can also create buses and processors manually, drawing inspiration from how it's done in NewFacade.
type Facade struct {
	commandsTopic func(commandName interface{}) string
	commandBus    *kafka.CommandBusWriteStream

	eventsTopic func(eventName interface{}) string
	eventBus    *kafka.EventBusWriteStream

	commandEventMarshaler eventstream.IEventMessageMarshaler
}

func (f Facade) CommandBus() *kafka.CommandBusWriteStream {
	return f.commandBus
}

func (f Facade) EventBus() *kafka.EventBusWriteStream {
	return f.eventBus
}

func (f Facade) CommandEventMarshaler() eventstream.IEventMessageMarshaler {
	return f.commandEventMarshaler
}

func NewFacade(config FacadeConfig) (*Facade, error) {
	if err := config.Validate(); err != nil {
		return nil, errors.Wrap(err, "invalid config")
	}

	c := &Facade{
		commandsTopic:         config.GenerateCommandsTopic,
		eventsTopic:           config.GenerateEventsTopic,
		commandEventMarshaler: config.CommandEventMarshaler,
	}

	if config.CommandsEnabled() {
		var err error
		c.commandBus = kafka.NewCommandbusWriteStream()
		if err != nil {
			return nil, errors.Wrap(err, "cannot create command bus")
		}
	} else {
		config.Logger.Info("Empty GenerateCommandsTopic, command bus will be not created")
	}
	if config.EventsEnabled() {
		var err error
		c.eventBus = kafka.NewEventBusWriteStream()
		if err != nil {
			return nil, errors.Wrap(err, "cannot create event bus")
		}
	} else {
		config.Logger.Info("Empty GenerateEventsTopic, event bus will be not created")
	}

	if config.CommandHandlers != nil {
		commandProcessor := NewCommandProcessor(
			config.CommandHandlers(c.commandBus, c.eventBus),
			config.GenerateCommandsTopic,
			config.CommandsConsumerConstructor,
			config.Logger,
			config.CommandEventMarshaler,
		)

		if err := commandProcessor.AddHandlersToRouter(config.Router); err != nil {
			return nil, err
		}
	}
	if config.EventHandlers != nil {
		eventProcessor := NewEventProcessor(
			config.EventHandlers(c.commandBus, c.eventBus),
			config.GenerateEventsTopic,
			config.EventsSubscriberConstructor,
			config.Logger,
			config.CommandEventMarshaler,
		)

		if err := eventProcessor.AddHandlersToRouter(config.Router); err != nil {
			return nil, err
		}
	}

	return c, nil
}
