CREATE TABLE IF NOT EXISTS project_legal_status(
  project_id uuid NOT NULL,  
  stake_holders TEXT,
  legal_status_idea TEXT,
  recommended_legal_status_idea TEXT,
  personal_wealth_security_required TEXT,
  company_tax_policy TEXT,
  social_security_scheme TEXT,
  situation_pole_emploi TEXT,
  locale_of_choice TEXT,
  management_stake TEXT,
  tax_system TEXT,
  property_owner TEXT,
  property_administration TEXT,
  domiciliation_company TEXT,
  professional_locale TEXT,
  localisation_financial_aid TEXT,
  lease_locale TEXT,
  verified_contract_commercial_leases TEXT,
  locale_activity_compatability TEXT,
  lease_contract_duration TEXT,
  lease_rental_price_fairness TEXT,
  verified_lease_price_renegiations TEXT,
  verified_payable_tentant_fees TEXT,
  verified_inventory TEXT,
  company_vat_regime TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  deleted_at TIMESTAMP,
  updated_at TIMESTAMP,
  PRIMARY KEY (project_id),
  CONSTRAINT fk_project_id FOREIGN KEY (project_id) REFERENCES projects (project_id) ON DELETE CASCADE
);
