# version of node to use
FROM node:15.4.0-alpine 
# define working directory for docker
ENV APPENV=dev
WORKDIR /usr/src/app
# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install
# copy all our source code into the working directory
COPY . ./

EXPOSE 9000

# Run the web service on container startup.
CMD [ "npm", "start" ]