variables:
  GCP_PROJECT_ID: lecoindesentrepreneurs
  IMAGE_NAME: bcp
  CLUSTER_ZONE: europe-west1-b
  CLUSTER_NAME: lecoindesentrepreneurs-bcp-production
  GOOGLE_CLOUD_IMAGE: gcr.io/lecoindesentrepreneurs/bcp-production-deployment:latest 
  GCR_HOST: eu.gcr.io

services:
  - docker:dind

stages:
  - publish
  - deploy

publish-image:
  stage: publish
  image: $GOOGLE_CLOUD_IMAGE
  script:
    - _init_
    - gcloud builds submit . --config=cloudbuild.yaml --substitutions COMMIT_SHA=$CI_COMMIT_SHA
  only:
    - master

deploy-image:
  stage: deploy
  image: $GOOGLE_CLOUD_IMAGE
  script:
    - _init_
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GCP_PROJECT_ID
    - git config --global user.name "base 10"
    - git config --global user.email "baraka00007x@gmail.com"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/baraka00007x/lecoindesentrepreneurs-bcp-chats.git
    - echo "deploying image:" ${GCR_HOST}/${GCP_PROJECT_ID}/${IMAGE_NAME}:${CI_COMMIT_SHA}
    - helm upgrade
      --reuse-values
      --set image.repository.backend="${GCR_HOST}/${GCP_PROJECT_ID}/${IMAGE_NAME}:${CI_COMMIT_SHA}"
      --wait
      --namespace production
      lecoindesentrepreneurs-bcp-production
      ./lecoindesentrepreneurs-bcp-chats
  only:
    - master

.functions: &functions |
    # Functions
    function _init_() {
        mkdir -p /etc/deploy
        echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
        gcloud config set project $GCP_PROJECT_ID
    }

before_script:
- *functions

