steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/bcp:$COMMIT_SHA' , '.']
images:
- 'eu.gcr.io/$PROJECT_ID/bcp:$COMMIT_SHA'
logsBucket: 'gs://lecoindesentrepreneurs-bcp-gitlab-gke-cloudbuild-logs/'
